#!/usr/bin/env bash

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
ALL_SERVICES="lunch-bot"

if [ -n "$(git status --porcelain)" ]; then
  echo "✋ Uncommitted local changes!" >&2
  exit 1
fi

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${SERVICES:-}" ]; then
  echo "✋ Missing SERVICES!" >&2
  exit 1
fi

if [ "${SERVICES}" == "all" ]; then
  SERVICES=${ALL_SERVICES}
  echo "🚧 Building all services! (${SERVICES})" >&2
fi

if [ -z "${TAG:-}" ]; then
  TAG="$(git rev-parse --short HEAD)"
  echo "🚧 Using generated tag! (${TAG})" >&2
fi

IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
for SERVICE in "${SERVICES_ARR[@]}"; do
  gcloud builds submit "${ROOT}" \
    --project "${PROJECT_ID}" \
    --config "${ROOT}/builders/build.yaml" \
    --substitutions "_SERVICE=${SERVICE},_TAG=${TAG}" \
    &
done

wait
