#!/usr/bin/env bash

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
ALL_SERVICES="lunch-bot"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${REGION:-}" ]; then
  echo "✋ Missing REGION!" >&2
  exit 1
fi

if [ -z "${SERVICES:-}" ]; then
  echo "✋ Missing SERVICES!" >&2
  exit 1
fi

if [ "${SERVICES}" == "all" ]; then
  SERVICES="${ALL_SERVICES}"
  echo "🚧 Building all services! (${SERVICES})" >&2
fi

if [ -z "${REVISION:-}" ]; then
  echo "🚧 Using LATEST revision" >&2
  REVISION="LATEST"
fi

if [ -z "${PERCENTAGE:-}" ]; then
  echo "🚧 Moving 100% of traffic" >&2
  PERCENTAGE="100"
fi

IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
for SERVICE in "${SERVICES_ARR[@]}"; do
  gcloud builds submit --no-source \
    --project "${PROJECT_ID}" \
    --config "${ROOT}/builders/promote.yaml" \
    --substitutions "_REGION=${REGION},_REVISION=${REVISION},_PERCENTAGE=${PERCENTAGE},_SERVICE=${SERVICE}" \
    &
done

wait
